############################
## CHANGE THESE
############################

baseURL: "https://Archii0.github.io/archii0.github.io"
title: archii0.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
