############################
## CHANGE THESE
############################

baseURL: "https://archii0.github.io/"
title: archii0.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
