############################
## CHANGE THESE
############################

baseURL: "https://archii0.github.io/"
title: Archii0

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true


markup:
  _merge: deep
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(  
            - \)
        enable: true
params:
  math: true